In [25]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [1]:
!head ../train/local-test/test_dir/input/spam.csv

v1,v2,,,
ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",,,
ham,Ok lar... Joking wif u oni...,,,
spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's,,,
ham,U dun say so early hor... U c already then say...,,,
ham,"Nah I don't think he goes to usf, he lives around here though",,,
spam,"FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, �1.50 to rcv",,,
ham,Even my brother is not like to speak with me. They treat me like aids patent.,,,
ham,As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune,,,
spam,WINNER!! As a valued network customer you have been selected to receivea �900 prize reward! To claim call 09061701461. Claim 

In [5]:
df = pd.read_csv('../train/local-test/test_dir/input/spam.csv', encoding='ISO-8859-1')

In [7]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [8]:
# drop unnecessary columns
df = df.drop(["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], axis=1)

In [9]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [13]:
# rename columns to something better
df.columns = ['labels', 'data']

In [14]:
df.head()

labels                                               data
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [16]:
# create binary labels
df['b_labels'] = df['labels'].map({'ham': 0, 'spam': 1})
Y = df['b_labels'].values

In [20]:
df

labels                                               data  b_labels
0       ham  Go until jurong point, crazy.. Available only ...         0
1       ham                      Ok lar... Joking wif u oni...         0
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...         1
3       ham  U dun say so early hor... U c already then say...         0
4       ham  Nah I don't think he goes to usf, he lives aro...         0
5      spam  FreeMsg Hey there darling it's been 3 week's n...         1
6       ham  Even my brother is not like to speak with me. ...         0
7       ham  As per your request 'Melle Melle (Oru Minnamin...         0
8      spam  WINNER!! As a valued network customer you have...         1
9      spam  Had your mobile 11 months or more? U R entitle...         1
10      ham  I'm gonna be home soon and i don't want to tal...         0
11     spam  SIX chances to win CASH! From 100 to 20,000 po...         1
12     spam  URGENT! You have won a 1 week FREE membership ...         1
13      ham  I've been searching for the right words to tha...         0
14      ham                I HAVE A DATE ON SUNDAY WITH WILL!!         0
15     spam  XXXMobileMovieClub: To use your credit, click ...         1
16      ham                         Oh k...i'm watching here:)         0
17      ham  Eh u remember how 2 spell his name... Yes i di...         0
18      ham  Fine if thatåÕs the way u feel. ThatåÕs the wa...         0
19     spam  England v Macedonia - dont miss the goals/team...         1
20      ham          Is that seriously how you spell his name?         0
21      ham  I‰Û÷m going to try for 2 months ha ha only joking         0
22      ham  So Ì_ pay first lar... Then when is da stock c...         0
23      ham  Aft i finish my lunch then i go str down lor. ...         0
24      ham  Ffffffffff. Alright no way I can meet up with ...         0
25      ham  Just forced myself to eat a slice. I'm really ...         0
26      ham                     Lol your always so convincing.         0
27      ham  Did you catch the bus ? Are you frying an egg ...         0
28      ham  I'm back &amp; we're packing the car now, I'll...         0
29      ham  Ahhh. Work. I vaguely remember that! What does...         0
...     ...                                                ...       ...
5542    ham           Armand says get your ass over to epsilon         0
5543    ham             U still havent got urself a jacket ah?         0
5544    ham  I'm taking derek &amp; taylor to walmart, if I...         0
5545    ham      Hi its in durban are you still on this number         0
5546    ham         Ic. There are a lotta childporn cars then.         0
5547   spam  Had your contract mobile 11 Mnths? Latest Moto...         1
5548    ham                 No, I was trying it all weekend ;V         0
5549    ham  You know, wot people wear. T shirts, jumpers, ...         0
5550    ham        Cool, what time you think you can get here?         0
5551    ham  Wen did you get so spiritual and deep. That's ...         0
5552    ham  Have a safe trip to Nigeria. Wish you happines...         0
5553    ham                        Hahaha..use your brain dear         0
5554    ham  Well keep in mind I've only got enough gas for...         0
5555    ham  Yeh. Indians was nice. Tho it did kane me off ...         0
5556    ham  Yes i have. So that's why u texted. Pshew...mi...         0
5557    ham  No. I meant the calculation is the same. That ...         0
5558    ham                             Sorry, I'll call later         0
5559    ham  if you aren't here in the next  &lt;#&gt;  hou...         0
5560    ham                  Anything lor. Juz both of us lor.         0
5561    ham  Get me out of this dump heap. My mom decided t...         0
5562    ham  Ok lor... Sony ericsson salesman... I ask shuh...         0
5563    ham                                Ard 6 like dat lor.         0
5564    ham  Why don't you wait 'til at least wednesday to ... 

In [23]:
# split up data data
df_train, df_test, Ytrain, Ytest = train = train_test_split(df['data'], Y, test_size=0.33)

In [57]:
print(Ytest)
df_test


[1 0 0 ... 0 0 0]


3054    EASTENDERS TV Quiz. What FLOWER does DOT compa...
874     Talk With Yourself Atleast Once In A Day...!!!...
2971    Sary just need Tim in the bollox &it hurt him ...
1728    As per your request 'Maangalyam (Alaipayuthe)'...
4361    I can't right this second, gotta hit people up...
2190    Ooh, 4got, i'm gonna start belly dancing in mo...
497     Some of them told accenture is not confirm. Is...
3278    Solve d Case : A Man Was Found Murdered On  &l...
4788    We're on the opposite side from where we dropp...
89              Ela kano.,il download, come wen ur free..
1283                            Yes i thought so. Thanks.
2650    Do you like shaking your booty on the dance fl...
5393    All done, all handed in. Don't know if mega sh...
1802                        Ok lor thanx... ÌÏ in school?
2816    Gr8 Poly tones 4 ALL mobs direct 2u rply with ...
766     I'm nt goin, got somethin on, unless they meet...
3833           Watching tv lor. Nice one then i like lor.
5525    I want

In [26]:
# Convert sentences to sequences
MAX_VOCAB_SIZE = 20000
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE)
tokenizer.fit_on_texts(df_train)
sequences_train = tokenizer.texts_to_sequences(df_train)
sequences_test = tokenizer.texts_to_sequences(df_test)

In [27]:
# get word -> integer mapping
word2idx = tokenizer.word_index
V = len(word2idx)
print('Found %s unique tokens.' % V )

Found 7208 unique tokens.


In [28]:
# pad sequences so that we get a N x T matrix 
data_train = pad_sequences(sequences_train)
print('Shape of data train tensor:', data_train.shape)

# get sequence length
T = data_train.shape[1]

Shape of data train tensor: (3733, 162)


In [29]:
data_test = pad_sequences(sequences_test, maxlen=T)
print('Shape of data test tensor:', data_test.shape)

Shape of data test tensor: (1839, 162)


In [64]:
print(Ytest[1003])
Ytest
data_test[1003]


1


array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        120,  275, 1132,   29,    5, 1538,  952,  386,   27,  696, 1460,
         18, 2953,  108,   71,  241,   27, 1460,   

In [59]:
print(Ytest[2])
data_test[2]

0


array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0, 6271,   